create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ps_regs/live_seconds[0]} {ps_regs/live_seconds[1]} {ps_regs/live_seconds[2]} {ps_regs/live_seconds[3]} {ps_regs/live_seconds[4]} {ps_regs/live_seconds[5]} {ps_regs/live_seconds[6]} {ps_regs/live_seconds[7]} {ps_regs/live_seconds[8]} {ps_regs/live_seconds[9]} {ps_regs/live_seconds[10]} {ps_regs/live_seconds[11]} {ps_regs/live_seconds[12]} {ps_regs/live_seconds[13]} {ps_regs/live_seconds[14]} {ps_regs/live_seconds[15]} {ps_regs/live_seconds[16]} {ps_regs/live_seconds[17]} {ps_regs/live_seconds[18]} {ps_regs/live_seconds[19]} {ps_regs/live_seconds[20]} {ps_regs/live_seconds[21]} {ps_regs/live_seconds[22]} {ps_regs/live_seconds[23]} {ps_regs/live_seconds[24]} {ps_regs/live_seconds[25]} {ps_regs/live_seconds[26]} {ps_regs/live_seconds[27]} {ps_regs/live_seconds[28]} {ps_regs/live_seconds[29]} {ps_regs/live_seconds[30]} {ps_regs/live_seconds[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ps_regs/live_tenths[0]} {ps_regs/live_tenths[1]} {ps_regs/live_tenths[2]} {ps_regs/live_tenths[3]} {ps_regs/live_tenths[4]} {ps_regs/live_tenths[5]} {ps_regs/live_tenths[6]} {ps_regs/live_tenths[7]} {ps_regs/live_tenths[8]} {ps_regs/live_tenths[9]} {ps_regs/live_tenths[10]} {ps_regs/live_tenths[11]} {ps_regs/live_tenths[12]} {ps_regs/live_tenths[13]} {ps_regs/live_tenths[14]} {ps_regs/live_tenths[15]} {ps_regs/live_tenths[16]} {ps_regs/live_tenths[17]} {ps_regs/live_tenths[18]} {ps_regs/live_tenths[19]} {ps_regs/live_tenths[20]} {ps_regs/live_tenths[21]} {ps_regs/live_tenths[22]} {ps_regs/live_tenths[23]} {ps_regs/live_tenths[24]} {ps_regs/live_tenths[25]} {ps_regs/live_tenths[26]} {ps_regs/live_tenths[27]} {ps_regs/live_tenths[28]} {ps_regs/live_tenths[29]} {ps_regs/live_tenths[30]} {ps_regs/live_tenths[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list ps_regs/tenth_sec_pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list ps_regs/one_sec_pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list tenkhz_trig]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets pl_clk0]
